import Head from 'next/head'
import { Login } from '../src/pages/login'

export default function LoginPage() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Login />
        </>
    )
}
