import Head from 'next/head'
import { Register } from '@/pages/register'

export default function RegisterPage() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Register />
        </>
    )
}
